version: 2.1

jobs:
  build:
    docker:
       - image: "circleci/python:3.6.4"

       steps:
         - checkout
         - run: python3 calc.py 

 workflows:
       build_prog:
       jobs:
           -build
                   